apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: pn1m46mm8-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:aed879b6dd2510d7c6cc2b1d9c669b572e7ac03c@sha256:2b419a189de8a66dc0577b57e466aa07f46b891c4d8127632b69ab5ecad7ab75
          name: container-image
